### ISSUE TITLE
OpenGl_GraphicDriver.ChangeOptions Runtime Error

### ISSUE THREAD

**Issue by cylopa** [trelau/pyOCCT#69]
Can not change the graphics driver options.

from OCCT.Aspect import Aspect_DisplayConnection
from OCCT.OpenGl import OpenGl_GraphicDriver

aspect_display_connection = Aspect_DisplayConnection()
opengl_graphic_driver = OpenGl_GraphicDriver(aspect_display_connection)

opengl_graphic_driver.ChangeOptions().buffersNoSwap = True  # Throws the below runtime error.
#print(opengl_graphic_driver.Options())  # Throws the below runtime error.
#print(opengl_graphic_driver.ChangeOptions())  # Throws the below runtime error.

#RuntimeError: return_value_policy = copy, but type is non-copyable! (compile in debug mode for details)

**Comment by trelau** [comment]
Should be fixed by https://github.com/trelau/pyOCCT/commit/6e6c03559302f249efc64a9a9d04bf36156d0e6c
