### ISSUE TITLE
Example for writing STEP file?

### ISSUE THREAD

**Issue by aizvorski** [trelau/pyOCCT#70]
Hello, I'm trying out pyOCCT.  I need to programmatically create some geometry and save it as step.  Could you add an example for writing a step file?  Similar to examples/import_step.py but in the other direction :)

**Comment by trelau** [comment]
you can use this function or at least use it as a jumping off point for using the OCCT functions https://github.com/trelau/pyOCCT/blob/master/OCCT/Exchange/Basic.py#L109
